/**
 * IInterviewOpenV2HomeAi
 * @generated by v2mock import
 */
export interface IInterviewOpenV2HomeAi {
  result?: string;
  code?: string;
  data?: InterviewOpenV2HomeAiData;
  msg?: string;
}

export interface InterviewOpenV2HomeAiData {
  /** 展示方式 0-汇总展示 1-按天展示 */
  showType: integer;
  /** 日期tab */
  dayTab: string[];
  /** 面试列表 */
  dayInterviewList: InterviewOpenV2HomeAiDataDayInterviewListItem[];
}
