module.exports = {
  declare: {
    delay: 300,
    status: 200,
    body: {
      "result": "1",
      "code": "0",
      "msg": "@string",
      "data": {
        "showType": "@integer(1,3)",
        "dayTab": [
          "@string"
        ],
        "dayInterviewList": [
          {
            "date": "@date(\"yyyyMMdd\")",
            "count": "@integer(0,20)",
            "interviewList": [
              {
                "interviewDay": "@string",
                "interviewDateTime": "@datetime",
                "name": "@cname",
                "job": "@string",
                "jobid": "@integer(10000,99999)",
                "accountid": "@integer(10000,99999)",
                "status": "@integer(0,5)",
                "type": "@integer(1,3)",
                "typeDisplayName": "@cname",
                "typeIcon": "@image(\"200x200\")",
                "typePlatformName": "@cname",
                "roomUrl": "@url",
                "tel": "@string(\"number\",11)",
                "id": "@id",
                "userid": "@integer(10000,99999)",
                "attachUrl": "@url",
                "minutes": "@integer(15,60)",
                "cancel_reason": "@string",
                "meeting_platform": "@float(0,100,2,2)",
                "meeting_link": "@url",
                "meeting_code": "@string",
                "meeting_passcode": "@string",
                "formatted_meeting_info": "@string",
                "aiInterviewQuestionGenerateCode": "@integer(1,3)",
                "aiInterviewQuestionText": "@string",
                "aiInterviewQuestionHoverText": "@cword(3,8)",
                "aiInterviewReportGenerateCode": "@integer(1,3)",
                "aiInterviewReportText": "@string",
                "aiInterviewReportTextForApp": "@string",
                "aiInterviewReportHoverText": "@cword(3,8)",
                "aiInterviewReportSummary": "@cparagraph",
                "aiInterviewEnabled": "@integer(1,100)",
                "interviewerId": "@integer(1,100)",
                "meetingEnd": "@string",
                "aiInterviewProgress": "@float(0,100,2,2)",
                "aiInterviewResult": "@float(0,100,2,2)",
                "aiTimeType": "@integer(1,3)",
                "aiSettingId": "@integer(1,100)",
                "validityTime": "@integer(1,100)",
                "expectedEndDate": "@date(\"yyyyMMdd\")",
                "createDateTime": "@datetime",
                "createDay": "@string"
              },
              {
                "interviewDay": "@string",
                "interviewDateTime": "@datetime",
                "name": "@cname",
                "job": "@string",
                "jobid": "@integer(10000,99999)",
                "accountid": "@integer(10000,99999)",
                "status": "@integer(0,5)",
                "type": "@integer(1,3)",
                "typeDisplayName": "@cname",
                "typeIcon": "@image(\"200x200\")",
                "typePlatformName": "@cname",
                "roomUrl": "@url",
                "tel": "@string(\"number\",11)",
                "id": "@id",
                "userid": "@integer(10000,99999)",
                "attachUrl": "@url",
                "minutes": "@integer(15,60)",
                "cancel_reason": "@string",
                "meeting_platform": "@float(0,100,2,2)",
                "meeting_link": "@url",
                "meeting_code": "@string",
                "meeting_passcode": "@string",
                "formatted_meeting_info": "@string",
                "aiInterviewQuestionGenerateCode": "@integer(1,3)",
                "aiInterviewQuestionText": "@string",
                "aiInterviewQuestionHoverText": "@cword(3,8)",
                "aiInterviewReportGenerateCode": "@integer(1,3)",
                "aiInterviewReportText": "@string",
                "aiInterviewReportTextForApp": "@string",
                "aiInterviewReportHoverText": "@cword(3,8)",
                "aiInterviewReportSummary": "@cparagraph",
                "aiInterviewEnabled": "@integer(1,100)",
                "interviewerId": "@integer(1,100)",
                "meetingEnd": "@string",
                "aiInterviewProgress": "@float(0,100,2,2)",
                "aiInterviewResult": "@float(0,100,2,2)",
                "aiTimeType": "@integer(1,3)",
                "aiSettingId": "@integer(1,100)",
                "validityTime": "@integer(1,100)",
                "expectedEndDate": "@date(\"yyyyMMdd\")",
                "createDateTime": "@datetime",
                "createDay": "@string"
              }
            ]
          },
          {
            "date": "@date(\"yyyyMMdd\")",
            "count": "@integer(0,20)",
            "interviewList": [
              {
                "interviewDay": "@string",
                "interviewDateTime": "@datetime",
                "name": "@cname",
                "job": "@string",
                "jobid": "@integer(10000,99999)",
                "accountid": "@integer(10000,99999)",
                "status": "@integer(0,5)",
                "type": "@integer(1,3)",
                "typeDisplayName": "@cname",
                "typeIcon": "@image(\"200x200\")",
                "typePlatformName": "@cname",
                "roomUrl": "@url",
                "tel": "@string(\"number\",11)",
                "id": "@id",
                "userid": "@integer(10000,99999)",
                "attachUrl": "@url",
                "minutes": "@integer(15,60)",
                "cancel_reason": "@string",
                "meeting_platform": "@float(0,100,2,2)",
                "meeting_link": "@url",
                "meeting_code": "@string",
                "meeting_passcode": "@string",
                "formatted_meeting_info": "@string",
                "aiInterviewQuestionGenerateCode": "@integer(1,3)",
                "aiInterviewQuestionText": "@string",
                "aiInterviewQuestionHoverText": "@cword(3,8)",
                "aiInterviewReportGenerateCode": "@integer(1,3)",
                "aiInterviewReportText": "@string",
                "aiInterviewReportTextForApp": "@string",
                "aiInterviewReportHoverText": "@cword(3,8)",
                "aiInterviewReportSummary": "@cparagraph",
                "aiInterviewEnabled": "@integer(1,100)",
                "interviewerId": "@integer(1,100)",
                "meetingEnd": "@string",
                "aiInterviewProgress": "@float(0,100,2,2)",
                "aiInterviewResult": "@float(0,100,2,2)",
                "aiTimeType": "@integer(1,3)",
                "aiSettingId": "@integer(1,100)",
                "validityTime": "@integer(1,100)",
                "expectedEndDate": "@date(\"yyyyMMdd\")",
                "createDateTime": "@datetime",
                "createDay": "@string"
              },
              {
                "interviewDay": "@string",
                "interviewDateTime": "@datetime",
                "name": "@cname",
                "job": "@string",
                "jobid": "@integer(10000,99999)",
                "accountid": "@integer(10000,99999)",
                "status": "@integer(0,5)",
                "type": "@integer(1,3)",
                "typeDisplayName": "@cname",
                "typeIcon": "@image(\"200x200\")",
                "typePlatformName": "@cname",
                "roomUrl": "@url",
                "tel": "@string(\"number\",11)",
                "id": "@id",
                "userid": "@integer(10000,99999)",
                "attachUrl": "@url",
                "minutes": "@integer(15,60)",
                "cancel_reason": "@string",
                "meeting_platform": "@float(0,100,2,2)",
                "meeting_link": "@url",
                "meeting_code": "@string",
                "meeting_passcode": "@string",
                "formatted_meeting_info": "@string",
                "aiInterviewQuestionGenerateCode": "@integer(1,3)",
                "aiInterviewQuestionText": "@string",
                "aiInterviewQuestionHoverText": "@cword(3,8)",
                "aiInterviewReportGenerateCode": "@integer(1,3)",
                "aiInterviewReportText": "@string",
                "aiInterviewReportTextForApp": "@string",
                "aiInterviewReportHoverText": "@cword(3,8)",
                "aiInterviewReportSummary": "@cparagraph",
                "aiInterviewEnabled": "@integer(1,100)",
                "interviewerId": "@integer(1,100)",
                "meetingEnd": "@string",
                "aiInterviewProgress": "@float(0,100,2,2)",
                "aiInterviewResult": "@float(0,100,2,2)",
                "aiTimeType": "@integer(1,3)",
                "aiSettingId": "@integer(1,100)",
                "validityTime": "@integer(1,100)",
                "expectedEndDate": "@date(\"yyyyMMdd\")",
                "createDateTime": "@datetime",
                "createDay": "@string"
              }
            ]
          }
        ]
      }
    }
  }
};
