// ============================================================
// JSON Schema → mockjs template 生成器
// 输入: YApi res_body JSON Schema
// 输出: { result: "1", code: "0", msg: "", data: {...} }
// ============================================================

function rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }

// 类型 → mockjs 模板默认值
function mockjsDefault(key, type, description) {
  // 1. 字段名语义匹配
  var m = matchField(key);
  if (m) return m;

  // 2. description 枚举
  var e = parseEnum(description);
  if (e) return e;

  // 3. 按类型给默认 mockjs
  switch (type) {
    case 'string':    return '@string';
    case 'integer':   return '@integer(1,100)';
    case 'number':    return '@float(0,100,2,2)';
    case 'boolean':   return '@boolean()';
    case 'null':      return null;
    default:          return type || '@string';
  }
}

// 字段名 → mockjs 语义
function matchField(key) {
  var rules = [
    [/^result$/, '1'],
    [/^code$/, '0'],
    [/msg|message/, '@string'],
    [/email/i, '@email'],
    [/(phone|mobile|tel)/i, '@string("number",11)'],
    [/name|userName|realName/i, '@cname'],
    [/title/i, '@cword(4,12)'],
    [/avatar|image|img|icon/i, '@image("200x200")'],
    [/url|link|href|attach/i, '@url'],
    [/(\b|_)id\b/i, '@id'],
    [/(jobid|jobId|userid|userId|accountid)/i, '@integer(10000,99999)'],
    [/date\b/i, '@date("yyyyMMdd")'],
    [/(createTime|updateTime|addTime|upTime|datetime)/i, '@datetime'],
    [/type\b/i, '@integer(1,3)'],
    [/showType/i, '@integer(0,2)'],
    [/\bstatus\b/i, '@integer(0,5)'],
    [/minutes/i, '@integer(15,60)'],
    [/(count|total|num|pending|completed|expired)/i, '@integer(0,20)'],
    [/(width|height|size)/i, '@integer(1,9999)'],
    [/cancel_reason/i, ''],
    [/(displayName|displayText|hoverText)/i, '@cword(3,8)'],
    [/generateCode/i, '@integer(1,3)'],
    [/desc|remark|note|summary|markdown/i, '@cparagraph'],
  ];
  for (var i = 0; i < rules.length; i++) {
    if (rules[i][0].test(key)) return rules[i][1];
  }
  return null;
}

// 从 description 提取枚举: "0：选项0\n1：选项1" → mockjs pick
function parseEnum(desc) {
  if (!desc) return null;
  var values = [];
  // 格式: "0：选项" 或 "0-选项" 或 "0 :选项"
  var lines = (desc || '').split(/[\n\r]+/);
  for (var i = 0; i < lines.length; i++) {
    var m = lines[i].match(/^\s*(\d+|"[^"]*")\s*[：:\-]\s*(.+)/);
    if (m) values.push(m[1].replace(/^"|"$/g, ''));
  }
  if (values.length >= 2) {
    return '@pick([' + values.join(',') + '])';
  }
  return null;
}

// 主入口：JSON Schema → mockjs body 对象
function schemaToBody(schema) {
  if (!schema || !schema.properties) return {};

  var body = { result: '1', code: '0', msg: '', data: {} };

  for (var key in schema.properties) {
    if (key === 'result' || key === 'code' || key === 'msg') {
      body[key] = mockjsDefault(key, 'string', '');
      continue;
    }
    if (key === 'data') {
      body.data = buildObject(schema.properties.data);
      continue;
    }
    body[key] = buildField(key, schema.properties[key]);
  }

  return body;
}

function buildField(key, prop) {
  if (!prop) return '@string';

  var desc = prop.description || '';
  var type = Array.isArray(prop.type)
    ? prop.type.find(function (t) { return t !== 'null'; }) || prop.type[0]
    : (prop.type || 'string');

  if (type === 'object') return buildObject(prop);
  if (type === 'array') return buildArray(key, prop);
  return mockjsDefault(key, type, desc);
}

function buildObject(prop) {
  if (!prop || !prop.properties) return {};
  var obj = {};
  for (var key in prop.properties) {
    obj[key] = buildField(key, prop.properties[key]);
  }
  return obj;
}

function buildArray(key, prop) {
  if (!prop || !prop.items) return [];
  var isListKey = /list/i.test(key);
  var count = isListKey ? 2 : 1;

  var itemSchema = prop.items;
  var itemType = Array.isArray(itemSchema.type)
    ? itemSchema.type.find(function (t) { return t !== 'null'; }) || 'string'
    : (itemSchema.type || 'string');

  var arr = [];
  if (itemType === 'object' && itemSchema.properties) {
    for (var i = 0; i < count; i++) arr.push(buildObject(itemSchema));
  } else {
    var itemKey = key.replace(/s$/i, '').replace(/List$/i, '') || key;
    for (var i = 0; i < count; i++) arr.push(buildField(itemKey, itemSchema));
  }
  return arr;
}

// ---- JSON Schema → TypeScript ----

function toPascalCase(str) {
  return str.replace(/(^|_)([a-z])/g, function (_, __, c) { return c.toUpperCase(); });
}

function schemaToTS(schema, name) {
  if (!schema || !schema.properties) return '// 无类型定义\n';
  var interfaceName = 'I' + toPascalCase(name);
  var lines = [];
  var subInterfaces = [];

  lines.push('/**');
  lines.push(' * ' + interfaceName);
  lines.push(' * @generated by v2mock import');
  lines.push(' */');
  lines.push('export interface ' + interfaceName + ' {');

  for (var key in schema.properties) {
    var prop = schema.properties[key];
    var desc = prop.description || '';
    var tsType = propType(prop, key, subInterfaces, toPascalCase(name));

    if (desc) {
      var descLines = desc.split('\n');
      lines.push('  /** ' + descLines[0].trim() + ' */');
    }
    var optional = !schema.required || schema.required.indexOf(key) === -1 ? '?' : '';
    lines.push('  ' + key + optional + ': ' + tsType + ';');
  }

  lines.push('}');

  // 子接口
  for (var s = 0; s < subInterfaces.length; s++) {
    lines.push(''); lines.push(subInterfaces[s]);
  }

  return lines.join('\n') + '\n';
}

function propType(prop, key, subInterfaces, prefix) {
  if (!prop) return 'any';

  var type = Array.isArray(prop.type)
    ? prop.type.find(function (t) { return t !== 'null'; }) || prop.type[0]
    : (prop.type || 'string');

  var nullable = Array.isArray(prop.type) && prop.type.indexOf('null') !== -1 ? ' | null' : '';

  // enum 提取
  var desc = prop.description || '';
  var enumVals = [];
  var lm = desc.match(/(\d+)[：:]\s*[^\n]+/g);
  if (lm) {
    for (var ei = 0; ei < lm.length; ei++) {
      var em = lm[ei].match(/^(\d+)/);
      if (em) enumVals.push(em[1]);
    }
  }
  if (prop.enum && prop.enum.length) enumVals = prop.enum;

  if (enumVals.length > 0) {
    return enumVals.join(' | ') + (nullable || '');
  }

  if (type === 'array') {
    var itemType = 'any';
    if (prop.items) {
      if (prop.items.type === 'object' && prop.items.properties) {
        var subName = prefix + toPascalCase(key) + 'Item';
        subInterfaces.push(buildSubInterface(subName, prop.items));
        itemType = subName;
      } else {
        itemType = propType(prop.items, key, subInterfaces, prefix);
      }
    }
    return itemType + '[]' + (nullable || '');
  }

  if (type === 'object' && prop.properties) {
    var subName2 = prefix + toPascalCase(key);
    subInterfaces.push(buildSubInterface(subName2, prop));
    return subName2 + (nullable || '');
  }

  return type + (nullable || '');
}

function buildSubInterface(name, schema) {
  if (!schema || !schema.properties) return 'export interface ' + name + ' {}';
  var lines = ['export interface ' + name + ' {'];
  for (var key in schema.properties) {
    var prop = schema.properties[key];
    var desc = prop.description || '';
    if (desc) lines.push('  /** ' + desc.split('\n')[0].trim() + ' */');
    lines.push('  ' + key + ': ' + propType(prop, key, [], name) + ';');
  }
  lines.push('}');
  return lines.join('\n');
}

module.exports = { schemaToBody, schemaToTS };
